### ISSUE TITLE
Params for multiplex networks

### ISSUE THREAD

**Issue by siri-ius** [lblaoke/gCooL#1]
Hi,

thank you for publishing your implementation!
I would be interested to know if you plan to post/publish the parameters for multiplex networks used in your paper: IMDB and DBLP.
Also, it would be great to have a link to the datasets you have used such that reproducing results would be effortless.

Thank you!

**Comment by lblaoke** [comment]
The training cost is not too high. You can directly train from scratch.

Will update the dataset links in README.
